services:
  resources-cleaner-messaging-broker:
    image: rabbitmq:4.1-management  # includes web UI
    ports:
      - "5672:5672"
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - resources-cleaner-messaging-broker-data:/var/lib/rabbitmq
    restart: unless-stopped

  app-db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - app-db-data:/data/db
    restart: unless-stopped

  keys-db:
    image: valkey/valkey:8.1.1 # for open-source Redis
    ports:
      - "6379:6379"
    environment:
      VALKEY_EXTRA_FLAGS: "--appendonly yes --appendfsync everysec" # optimized for consistency, avoid duplicates
    volumes:
      - keys-db-data:/data
    restart: unless-stopped

  keys-db-test:
    image: valkey/valkey:8.1.1 # for open-source Redis
    ports:
      - "6380:6379"
    environment:
      VALKEY_EXTRA_FLAGS: "--save ''" # optimized for testing, data will always be flushed by tests
    restart: unless-stopped


volumes:
  resources-cleaner-messaging-broker-data:
  app-db-data:
  keys-db-data:
