services:
  resources-cleaner-messaging-broker:
    image: rabbitmq:4.1-management  # includes web UI
    ports:
      - "5672:5672"
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - resources-cleaner-messaging-broker-data:/var/lib/rabbitmq
    restart: unless-stopped

  free-keys-db:
    image: valkey/valkey:8.1.1
    ports:
      - "6379:6379"
    environment:
      VALKEY_EXTRA_FLAGS: "--appendonly yes --appendfsync everysec" # optimized for consistency, avoid duplicates
    volumes:
      - free-keys-db-data:/data
    restart: unless-stopped

  taken-keys-db:
    image: valkey/valkey:8.1.1
    ports:
      - "6380:6379"
    environment:
      VALKEY_EXTRA_FLAGS: "--save 300 1 --loglevel warning" # optimized for performance, all data isn't necessary
    volumes:
      - taken-keys-db-data:/data
    restart: unless-stopped

volumes:
  resources-cleaner-messaging-broker-data:
  free-keys-db-data:
  taken-keys-db-data:
