// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: keys-contract.proto

package keys

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Keys_GetKey_FullMethodName     = "/keys.Keys/GetKey"
	Keys_ReleaseKey_FullMethodName = "/keys.Keys/ReleaseKey"
)

// KeysClient is the client API for Keys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeysClient interface {
	GetKey(ctx context.Context, in *Void, opts ...grpc.CallOption) (*KeyResponse, error)
	ReleaseKey(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Void, error)
}

type keysClient struct {
	cc grpc.ClientConnInterface
}

func NewKeysClient(cc grpc.ClientConnInterface) KeysClient {
	return &keysClient{cc}
}

func (c *keysClient) GetKey(ctx context.Context, in *Void, opts ...grpc.CallOption) (*KeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyResponse)
	err := c.cc.Invoke(ctx, Keys_GetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keysClient) ReleaseKey(ctx context.Context, in *KeyRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, Keys_ReleaseKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeysServer is the server API for Keys service.
// All implementations must embed UnimplementedKeysServer
// for forward compatibility.
type KeysServer interface {
	GetKey(context.Context, *Void) (*KeyResponse, error)
	ReleaseKey(context.Context, *KeyRequest) (*Void, error)
	mustEmbedUnimplementedKeysServer()
}

// UnimplementedKeysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeysServer struct{}

func (UnimplementedKeysServer) GetKey(context.Context, *Void) (*KeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedKeysServer) ReleaseKey(context.Context, *KeyRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseKey not implemented")
}
func (UnimplementedKeysServer) mustEmbedUnimplementedKeysServer() {}
func (UnimplementedKeysServer) testEmbeddedByValue()              {}

// UnsafeKeysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeysServer will
// result in compilation errors.
type UnsafeKeysServer interface {
	mustEmbedUnimplementedKeysServer()
}

func RegisterKeysServer(s grpc.ServiceRegistrar, srv KeysServer) {
	// If the following call pancis, it indicates UnimplementedKeysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Keys_ServiceDesc, srv)
}

func _Keys_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keys_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).GetKey(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keys_ReleaseKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).ReleaseKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keys_ReleaseKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).ReleaseKey(ctx, req.(*KeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Keys_ServiceDesc is the grpc.ServiceDesc for Keys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Keys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keys.Keys",
	HandlerType: (*KeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKey",
			Handler:    _Keys_GetKey_Handler,
		},
		{
			MethodName: "ReleaseKey",
			Handler:    _Keys_ReleaseKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keys-contract.proto",
}
