// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: keys-contract.proto

package keys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_keys_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_keys_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_keys_contract_proto_rawDescGZIP(), []int{0}
}

type KeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyResponse) Reset() {
	*x = KeyResponse{}
	mi := &file_keys_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyResponse) ProtoMessage() {}

func (x *KeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keys_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyResponse.ProtoReflect.Descriptor instead.
func (*KeyResponse) Descriptor() ([]byte, []int) {
	return file_keys_contract_proto_rawDescGZIP(), []int{1}
}

func (x *KeyResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type KeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRequest) Reset() {
	*x = KeyRequest{}
	mi := &file_keys_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRequest) ProtoMessage() {}

func (x *KeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keys_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRequest.ProtoReflect.Descriptor instead.
func (*KeyRequest) Descriptor() ([]byte, []int) {
	return file_keys_contract_proto_rawDescGZIP(), []int{2}
}

func (x *KeyRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_keys_contract_proto protoreflect.FileDescriptor

const file_keys_contract_proto_rawDesc = "" +
	"\n" +
	"\x13keys-contract.proto\x12\x04keys\"\x06\n" +
	"\x04Void\"\x1f\n" +
	"\vKeyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"\x1e\n" +
	"\n" +
	"KeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key2_\n" +
	"\x04Keys\x12)\n" +
	"\x06GetKey\x12\n" +
	".keys.Void\x1a\x11.keys.KeyResponse\"\x00\x12,\n" +
	"\n" +
	"ReleaseKey\x12\x10.keys.KeyRequest\x1a\n" +
	".keys.Void\"\x00B\aZ\x05/keysb\x06proto3"

var (
	file_keys_contract_proto_rawDescOnce sync.Once
	file_keys_contract_proto_rawDescData []byte
)

func file_keys_contract_proto_rawDescGZIP() []byte {
	file_keys_contract_proto_rawDescOnce.Do(func() {
		file_keys_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keys_contract_proto_rawDesc), len(file_keys_contract_proto_rawDesc)))
	})
	return file_keys_contract_proto_rawDescData
}

var file_keys_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_keys_contract_proto_goTypes = []any{
	(*Void)(nil),        // 0: keys.Void
	(*KeyResponse)(nil), // 1: keys.KeyResponse
	(*KeyRequest)(nil),  // 2: keys.KeyRequest
}
var file_keys_contract_proto_depIdxs = []int32{
	0, // 0: keys.Keys.GetKey:input_type -> keys.Void
	2, // 1: keys.Keys.ReleaseKey:input_type -> keys.KeyRequest
	1, // 2: keys.Keys.GetKey:output_type -> keys.KeyResponse
	0, // 3: keys.Keys.ReleaseKey:output_type -> keys.Void
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keys_contract_proto_init() }
func file_keys_contract_proto_init() {
	if File_keys_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keys_contract_proto_rawDesc), len(file_keys_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keys_contract_proto_goTypes,
		DependencyIndexes: file_keys_contract_proto_depIdxs,
		MessageInfos:      file_keys_contract_proto_msgTypes,
	}.Build()
	File_keys_contract_proto = out.File
	file_keys_contract_proto_goTypes = nil
	file_keys_contract_proto_depIdxs = nil
}
